apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manuela-quickstart-messaging-role-binding
  namespace: manuela-quickstart-messaging
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops

